In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
# read Data
df = pd.read_csv('covid.csv')

In [4]:
df.head()

id  sex  patient_type  entry_date date_symptoms   date_died  intubed  \
0  16169f    2             1  04-05-2020    02-05-2020  9999-99-99       97   
1  1009bf    2             1  19-03-2020    17-03-2020  9999-99-99       97   
2  167386    1             2  06-04-2020    01-04-2020  9999-99-99        2   
3  0b5948    2             2  17-04-2020    10-04-2020  9999-99-99        2   
4  0d01b5    1             2  13-04-2020    13-04-2020  22-04-2020        2   

   pneumonia  age  pregnancy  ...  inmsupr  hypertension  other_disease  \
0          2   27         97  ...        2             2              2   
1          2   24         97  ...        2             2              2   
2          2   54          2  ...        2             2              2   
3          1   30         97  ...        2             2              2   
4          2   60          2  ...        2             1              2   

   cardiovascular  obesity  renal_chronic  tobacco  contact_other_covid  \
0               2        2              2        2                    2   
1               2        2              2        2                   99   
2               2        1              2        2                   99   
3               2        2              2        2                   99   
4               1        2              2        2                   99   

   covid_res  icu  
0          1   97  
1          1   97  
2          1    2  
3          1    2  
4          1    2  

[5 rows x 23 columns]

In [5]:
df.describe()


sex   patient_type        intubed      pneumonia  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean        1.506726       1.215165      76.562952       1.846262   
std         0.499955       0.410937      39.058676       0.560939   
min         1.000000       1.000000       1.000000       1.000000   
25%         1.000000       1.000000      97.000000       2.000000   
50%         2.000000       1.000000      97.000000       2.000000   
75%         2.000000       1.000000      97.000000       2.000000   
max         2.000000       2.000000      99.000000      99.000000   

                 age      pregnancy       diabetes           copd  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean       42.622483      50.400692       2.210633       2.280221   
std        16.659973      47.501579       5.683523       5.327832   
min         0.000000       1.000000       1.000000       1.000000   
25%        31.000000       2.000000       2.000000       2.000000   
50%        41.000000      97.000000       2.000000       2.000000   
75%        53.000000      97.000000       2.000000       2.000000   
max       120.000000      98.000000      98.000000      98.000000   

              asthma        inmsupr   hypertension  other_disease  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean        2.265029       2.319628       2.145774       2.410030   
std         5.334658       5.667381       5.459866       6.489959   
min         1.000000       1.000000       1.000000       1.000000   
25%         2.000000       2.000000       2.000000       2.000000   
50%         2.000000       2.000000       2.000000       2.000000   
75%         2.000000       2.000000       2.000000       2.000000   
max        98.000000      98.000000      98.000000      98.000000   

       cardiovascular        obesity  renal_chronic        tobacco  \
count   566602.000000  566602.000000  566602.000000  566602.000000   
mean         2.286157       2.138905       2.283765       2.238360   
std          5.438405       5.395578       5.393232       5.571901   
min          1.000000       1.000000       1.000000       1.000000   
25%          2.000000       2.000000       2.000000       2.000000   
50%          2.000000       2.000000       2.000000       2.000000   
75%          2.000000       2.000000       2.000000       2.000000   
max         98.000000      98.000000      98.000000      98.000000   

       contact_other_covid      covid_res            icu  
count        566602.000000  566602.000000  566602.000000  
mean             31.573034       1.728651      76.562864  
std              45.082123       0.658710      39.059060  
min               1.000000       1.000000       1.000000  
25%               1.000000       1.000000      97.000000  
50%               2.000000       2.000000      97.000000  
75%              99.000000       2.000000      97.000000  
max              99.000000       3.000000      99.000000

In [6]:
df['patient_type'].value_counts()

1    444689
2    121913
Name: patient_type, dtype: int64

In [7]:
# Shape of Data
df.shape

(566602, 23)

In [8]:
# drop some colums we donot need like dates and id
df.drop(columns={'entry_date','date_died','date_symptoms', 'inmsupr' ,'id', 'patient_type', 'pregnancy', 'other_disease'},axis=1,inplace=True)
df.shape

(566602, 15)

In [9]:
df.shape

(566602, 15)

In [11]:
df['intubed'].value_counts()

97    444689
2     111824
1       9965
99       124
Name: intubed, dtype: int64

In [12]:
df['obesity'].value_counts()

2     472549
1      92272
98      1781
Name: obesity, dtype: int64

In [13]:
df['cardiovascular'].value_counts()

2     552005
1      12775
98      1822
Name: cardiovascular, dtype: int64

In [14]:
df['renal_chronic'].value_counts()

2     553560
1      11250
98      1792
Name: renal_chronic, dtype: int64

In [15]:
df['contact_other_covid'].value_counts()

1     221867
99    175031
2     169704
Name: contact_other_covid, dtype: int64

In [16]:
# CHECK  NULL Values
df.isnull().sum()

sex                    0
intubed                0
pneumonia              0
age                    0
diabetes               0
copd                   0
asthma                 0
hypertension           0
cardiovascular         0
obesity                0
renal_chronic          0
tobacco                0
contact_other_covid    0
covid_res              0
icu                    0
dtype: int64

In [17]:
df['covid_res'].value_counts()

2    279035
1    220657
3     66910
Name: covid_res, dtype: int64

In [18]:
X = df[['sex','intubed','pneumonia','age',
       'diabetes','copd','asthma','hypertension',
       'cardiovascular', 'obesity', 'renal_chronic',
       'tobacco', 'contact_other_covid', 'icu']]
print(X)

        sex  intubed  pneumonia  age  diabetes  copd  asthma  hypertension  \
0         2       97          2   27         2     2       2             2   
1         2       97          2   24         2     2       2             2   
2         1        2          2   54         2     2       2             2   
3         2        2          1   30         2     2       2             2   
4         1        2          2   60         1     2       2             1   
...     ...      ...        ...  ...       ...   ...     ...           ...   
566597    2       97          2   58         1     2       2             2   
566598    1       97          2   48         2     2       2             2   
566599    1        2          1   49         2     2       2             2   
566600    1       97          1   43         2     2       2             2   
566601    2       97          1   65         1     2       2             1   

        cardiovascular  obesity  renal_chronic  tobacco  contac

In [19]:
df.shape

(566602, 15)

In [20]:
df['covid_res'].replace([1,2,3],[1,0,2],inplace=True)
df['covid_res'].value_counts().to_frame()

covid_res
0     279035
1     220657
2      66910

In [21]:
#y = df[{'covid_res'}]
y = df['covid_res']
print(y)
y.shape

0         1
1         1
2         1
3         1
4         1
         ..
566597    2
566598    2
566599    2
566600    2
566601    2
Name: covid_res, Length: 566602, dtype: int64


(566602,)

In [22]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [23]:
# apply Models (Desicion tree, SVC, Random Forest, Logistic Regression)
from sklearn.tree import DecisionTreeClassifier
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.svm import SVC

In [24]:
# instance of model
treeModel = DecisionTreeClassifier()

In [25]:
treeModel.fit(x_train, y_train)

DecisionTreeClassifier()

In [26]:
predTree = treeModel.predict(x_test)

In [27]:
print(predTree)

[0 0 0 ... 1 0 0]


In [28]:
from sklearn.metrics import accuracy_score

In [29]:
score = accuracy_score(y_test, predTree)

In [30]:
print(score)

0.5476919547127187


In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
ranModel = RandomForestClassifier(n_estimators=200)
ranModel

RandomForestClassifier(n_estimators=200)

In [33]:
ranModel.fit(x_test, y_test)

RandomForestClassifier(n_estimators=200)

In [34]:
ranForestPred = ranModel.predict(x_test)

In [35]:
ranForestPred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [37]:
ranModel.score(x_test, y_test)

0.6391489662110289

In [38]:
ran_score = accuracy_score(y_test, ranForestPred)
ran_score

0.6391489662110289

In [39]:
pd.to_pickle(ranModel, 'covid_model.pickle')

In [40]:
model = pd.read_pickle('covid_model.pickle')

In [41]:
result = model.predict([[1, 1, 1, 45, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
result

c:\users\adib-pc\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [147]:
#import pickle as plk

In [148]:
#with open('covid_model', 'wb') as file:
    #covid_model = plk.dump(ranModel, file)

In [121]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.linear_model import LogisticRegression
#logModel = LogisticRegression(max_iter=100)
#logModel.fit(x_test, y_test)